server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CloudDatabase/orderdata?useSSL=false
    username: root
    password: 264017
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: productshow
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址

#logging:
#  level:


logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS