server:
  port: 2000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdata?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 264017
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: userclient
  redis:
    host: 192.168.1.126
    port: 6379
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8    #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 1000ms    #连接等待时间
    timeout: 30
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间格式
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.zw.graducate.entity
  configuration:
    map-underscore-to-camel-case: true

  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址

#logging:
#  level:


logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS