server:
  port: 7777

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/log?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 264017
        driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: middleware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间格式
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.zw.graducate.entity
  configuration:
    map-underscore-to-camel-case: true

  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址

#logging:
#  level:


logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS